{"name": "Принять заказ с несуществующим id курьера", "status": "passed", "description": "Попытка принять заказ с несуществующим id курьера должна вернуть ошибку 404", "start": 1701451454962, "stop": 1701451456105, "uuid": "9c8bedb6-3a17-4c37-8e2a-3bcd082747c5", "historyId": "99b633f7f4eef382eb815dbb1072cd6e", "testCaseId": "99b633f7f4eef382eb815dbb1072cd6e", "fullName": "tests.test_orders_accept.TestOrdersAccept#test_accept_order_with_wrong_courier_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "Ya"}, {"name": "thread", "value": "34240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_orders_accept"}]}