{"name": "Принять заказ с несуществующим id заказа", "status": "passed", "description": "Попытка принять заказ с несуществующим id заказа должна вернуть ошибку 404", "start": 1701451456953, "stop": 1701451458036, "uuid": "9e806f82-79a4-4231-a6ec-3587579b107d", "historyId": "b7cfa665b2adacbb426bc69415e11d5a", "testCaseId": "b7cfa665b2adacbb426bc69415e11d5a", "fullName": "tests.test_orders_accept.TestOrdersAccept#test_accept_order_with_wrong_order_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_orders_accept"}, {"name": "subSuite", "value": "TestOrdersAccept"}, {"name": "host", "value": "Ya"}, {"name": "thread", "value": "34240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_orders_accept"}]}